[package]
name = "rust_webserver"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
dotenvy = "0.15.7"
hyper = "1.7.0"
log = "0.4.28"
log4rs = "1.4.0"
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
tower = "0.5.2"
